version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

dockers:
  - id: goreleaser-test-amd64
    goos: linux
    goarch: amd64
    skip_push: false
    use: buildx
    dockerfile: 'Dockerfile.goreleaser'
    image_templates:
      - "mehmettokgoz/goreleaser-test:latest-amd64"
      - "mehmettokgoz/goreleaser-test:{{ .Tag }}-amd64"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
  - id: goreleaser-test-arm64
    goos: linux
    goarch: arm64
    skip_push: false
    use: buildx
    dockerfile: 'Dockerfile.goreleaser'
    image_templates:
      - "mehmettokgoz/goreleaser-test:latest-arm64v8"
      - "mehmettokgoz/goreleaser-test:{{ .Tag }}-arm64v8"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64"
docker_manifests:
  - name_template: mehmettokgoz/goreleaser-test:latest
    image_templates:
      - mehmettokgoz/goreleaser-test:latest-amd64
      - mehmettokgoz/goreleaser-test:latest-arm64v8
  - name_template: mehmettokgoz/goreleaser-test:{{ .Tag }}
    image_templates:
      - mehmettokgoz/goreleaser-test:{{ .Tag }}-amd64
      - mehmettokgoz/goreleaser-test:{{ .Tag }}-arm64v8


archives:
    - format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL or empty if its private hosted.
  github:
    owner: mehmettokgoz
    name: goreleaser-test
